baseurl = ""
languageCode = "en-us"
title = "Open States Blog"
theme = "hemingway"
googleAnalytics = "UA-84709685-2"

[params]

[[params.social]]
url = "https://github.com/openstates"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/openstates"
fa_icon = "fa-twitter"
